volumes:
  pgdata:
    driver: local

networks:
  egov-network:
    driver: bridge
    attachable: true

services:
  postgres:
    container_name: egov-db
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - egov-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  keycloak:
    container_name: egov-keycloak
    image: quay.io/keycloak/keycloak:legacy
    networks:
      - egov-network
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  api_dev:
    container_name: egov-api-dev
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    networks:
      - egov-network
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - keycloak

  api_prod:
    container_name: egov-api-prod
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - egov-network
    depends_on:
      - postgres
      - keycloak
