volumes:
  egov_ai_pgdata:
    driver: local

services:
  postgres:
    container_name: egov_db
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - egov_ai_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  keycloak:
    container_name: egov_keycloak
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  dev:
    container_name: egov_api
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - keycloak
