FROM node:20-alpine

WORKDIR /app

RUN apk update
RUN apk upgrade
RUN npm upgrade -g
RUN npm i -g pnpm

COPY package*.json ./
RUN pnpm install

COPY . .

EXPOSE 3000
CMD [ "pnpm", "run", "start:dev" ]
